# Generated by Django 4.1.7 on 2023-04-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_skills', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(to='course.skills'),
        ),
    ]
