# Generated by Django 4.1.7 on 2023-04-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_available_sits_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_resume',
            field=models.TextField(default='resume of teacher'),
            preserve_default=False,
        ),
    ]
